#!/bin/bash

SCRIPT_NAME=$(basename $0)

function help {
	echo -e "usage: ${SCRIPT_NAME} [-h] [-a] [-c] [-s]"
	echo -e "\nHelp documentation for ${SCRIPT_NAME}:\n"
	echo -e "-h, --help             Show this message"
	echo -e "-r, --raise            Raise volume on default sink by 5%"
	echo -e "-l, --lower            Lower volume on default sink by 5%"
	echo -e "-m, --mute             Toggle mute on default sink"
	echo -e "-d, --default-sink     Set the default sink (specified by index from -s option)"
	echo -e "-s, --sinks            List sinks"
	echo ""
	exit 1
}

OPTS=$(getopt -o h,r,l,m,d:,s --long help,raise,lower,mute,default-sink:,sinks -- "$@")

# Option parsing failed
if [ $? -ne 0 ]; then
	help
fi

eval set -- "$OPTS"

# Process options
while true; do
	case "$1" in
		-h|--help)
			help
			shift ;;
		-r|--raise)
			$(pactl set-sink-volume @DEFAULT_SINK@ +5%)
			exit 0
			shift ;;
		-l|--lower)
			$(pactl set-sink-volume @DEFAULT_SINK@ -5%)
			exit 0
			shift ;;
		-m|--mute)
			$(pactl set-sink-mute @DEFAULT_SINK@ toggle)
			exit 0
			shift ;;
		-d|--default-sink)
			$(pactl set-default-sink $2)
			exit 0
			shift 2 ;;
		-s|--sinks)
			echo -e "Index\tSink"
			echo -e "-----\t----"
			sinks=$(pacmd list-sinks | grep name: | sed -E 's/name: <(.*)>/\1/')
			i=0
			for s in $sinks; do
				echo -e "$i\t$s"
				i=$(($i + 1))
			done
			exit 0
			shift ;;
		*)
			break ;;
	esac
done
